name: Generate prebuilds

on:
  workflow_dispatch:
    inputs:
      module_version:
        description: 'Module version'
        required: true
        default: 'latest'

env:
  NODE_VERSION: 18
  MODULE_NAME: "sodium-native"

jobs:
  build:
    strategy:
      matrix:
        platform: [android]
        arch: [arm64, x64, arm]
    uses: digidem/nodejs-mobile-prebuilds/.github/workflows/prebuild.yml@main
    with:
      module_name: "sodium-native"
      module_version: ${{ inputs.module_version }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: prebuilds

      - run: ls -alR prebuilds

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "prebuilds/*"
          artifactErrorsFailBuild: true
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ needs.build.outputs.version }}
