name: Generate prebuilds

on:
  workflow_dispatch:
    inputs:
      module_version:
        description: 'Module version'
        required: true
        default: 'latest'

env:
  NODE_VERSION: 18
  MODULE_NAME: "sodium-native"

jobs:
  build:
    strategy:
      matrix:
        platform: [android]
        arch: [arm64, x64, arm]
    uses: digidem/nodejs-mobile-prebuilds/.github/workflows/prebuild.yml@main
    with:
      module_name: "sodium-native"
      module_version: ${{ inputs.module_version }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}

  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.MODULE_NAME }}-${{ env.MODULE_VERSION }}-*/*.tar.gz"
          artifactErrorsFailBuild: true
          allowUpdates: true
          replacesArtifacts: true
